### ISSUE TITLE
Create basic working extension as a baseline

### ISSUE THREAD

**Issue by jagmeetb** [yevseytsev/SenecaBlackboardExtension#2] opened 2018-11-05 22:56 UTC
- Look at other extensions to see the bare minimum to get a working extension (something that serves a similar purpose of improving webpages by modifying elements like refined-github etc)
- update something simple like add/remove/update a single element (eg. add link to seneca email, remove some urls, change text size/color)

**Comment by deepanjali19** [comment] 2018-11-06 09:50
I will work on it!

**Comment by deepanjali19** [comment] 2018-11-06 21:30
Dupe of [issue](https://github.com/yevseytsev/SenecaBlackboardExtension/issues/6), which is already closed.

**Comment by yevseytsev** [comment] 2018-11-07 23:54
@jagmeetb @deepanjali19 this is done! Thank you for your work!

**Closed by yevseytsev** 2018-11-07 23:54 UTC
